kafka:
  enabled: true
  replicaCount: 1  # Only 1 broker (small footprint)
  kraft:
    enabled: true  # Enable KRaft mode
  persistence:
    enabled: true
    size: 10Gi
  logPersistence:
    enabled: true  # Enable log persistence for brokers
  auth:
    clientProtocol: sasl
    interBrokerProtocol: sasl
    sasl:
      jaas:
        clientUsers:
          - user1
        clientPasswords:
          - password1
        interBrokerUser: inter_broker_user
        interBrokerPassword: inter_broker_pass
  extraEnvVars:
    - name: KAFKA_NODE_ID
      value: "1"
    - name: KAFKA_PROCESS_ROLES
      value: "broker"
    - name: KAFKA_CONTROLLER_QUORUM_VOTERS
      value: "0@kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9093"
    - name: KAFKA_LISTENERS
      value: "CLIENT://:9092,INTERNAL://:9094"
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: "CLIENT:SASL_PLAINTEXT,INTERNAL:SASL_PLAINTEXT"
    - name: KAFKA_INTER_BROKER_LISTENER_NAME
      value: "INTERNAL"
  podLabels:
    app.kubernetes.io/component: broker