controller:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: true
    size: 10Gi
  extraEnvVars:
    - name: KAFKA_NODE_ID
      value: "0"
    - name: KAFKA_PROCESS_ROLES
      value: "controller"
    - name: KAFKA_CONTROLLER_QUORUM_VOTERS
      value: "0@kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9093"
    - name: KAFKA_LISTENERS
      value: "CONTROLLER://:9093"
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: "CONTROLLER:SASL_PLAINTEXT"
    - name: KAFKA_CONTROLLER_LISTENER_NAMES
      value: "CONTROLLER"
  podLabels:
    app.kubernetes.io/component: controller